### ISSUE TITLE
大佬，可以考虑使用别的方式授权吗？

### ISSUE THREAD

**Issue by loeveo** [TheValkyrja/Anthropic2Vertex#1]
因为便宜的gcp账号是不能够使用这个玩意儿的，他不允许创建密钥，就算是使用别的个人账户创建的服务账号，也无法添加

**Comment by TheValkyrja** [comment]
我会考虑新的授权方式，但是基于要修改的复杂性短时间内没法支持，如果使用个人账户进行授权，需要安装的依赖比较多，我要研究优化策略。

**Comment by TheValkyrja** [comment]
基于gcp vertexAI可能存在的（使用低质量堆量的账号池）的滥用情况、GCP安全政策及其他验证方式实现的复杂性，此提议暂且搁置。
将会在之后的将来再考虑这个提议的实现。

Close as cancelled.
