### ISSUE TITLE
可不可以增加一个error回复是的提示？

### ISSUE THREAD

**Issue by tonnyjb546** [TheValkyrja/Anthropic2Vertex#3]
当anthropic.APIStatusError: {'type': 'error', 'error': {'details': None, 'type': 'overloaded_error', 'message': 'Overloaded'}}时，程序会出错。
能不能这对这个返回一个错误提示。否则sillytavern会一直等待回复输出。

**Comment by TheValkyrja** [comment]
这个问题在目前的工作进度中已经完成了，但是我好懒而且好忙所以这边不知道什么时候能传上来。

**Comment by TheValkyrja** [comment]
已经实现了对于这个问题的检查和报错逻辑，但是我希望更多模仿原生API的行为，因此报错部分留空不做处理。
Vertex已经将这个报错修改为429错误，这在最新的release中可以被直接捕获。

close as complete.
