### ISSUE TITLE
佬，是否可以考虑增加一个多账号或多密钥的导入呢

### ISSUE THREAD

**Issue by Znpos901** [TheValkyrja/Anthropic2Vertex#4]
现在只能塞一个账号，但150刀的试用账号短时间内用得多了会卡你的使用频率甚至短时间连不了，换别的号就能用，如果能增加一个定期或定次多账号轮换就好了

**Comment by TheValkyrja** [comment]
会做，下个版本打上去。2024年7月16日 22:19，Znpos901 ***@***.***>写道：
现在只能塞一个账号，但150刀的试用账号短时间内用得多了会卡你的使用频率甚至短时间连不了，换别的号就能用，如果能增加一个定期或定次多账号轮换就好了

**Comment by TheValkyrja** [comment]
但是可能要一些时间，因为我之前花时间去重构了一遍代码，要把它再这个旧项目上再实现比较麻烦。

**Comment by TheValkyrja** [comment]
新功能已经包含在最新的release中实现。

close as complete.
